# Generated by Django 2.2.3 on 2020-05-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
