# Generated by Django 2.2.3 on 2020-06-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='org/%Y/%m', verbose_name='机构封面'),
        ),
    ]
