# Generated by Django 2.2.3 on 2020-05-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('qd', '前端开发'), ('hd', '后端开发')], default='后端开发', max_length=25, verbose_name='课程类别'),
        ),
    ]
