# Generated by Django 2.2.3 on 2020-05-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200518_1932'),
        ('courses', '0005_auto_20200520_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_notice',
            field=models.CharField(default='新公告', max_length=200, verbose_name='课程公告'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Teacher', verbose_name='讲师'),
        ),
    ]
