# Generated by Django 2.2.3 on 2020-06-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200520_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='file_upload',
            field=models.FileField(default='static/video/', max_length=200, upload_to='media/video/%Y/%m', verbose_name='视频'),
        ),
    ]
