# Generated by Django 2.2.3 on 2020-06-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200605_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceinfo',
            name='down_load',
            field=models.FileField(max_length=200, upload_to='media/source/%Y/%m', verbose_name='下载路径'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_upload',
            field=models.FileField(max_length=200, upload_to='media/video/%Y/%m', verbose_name='视频'),
        ),
    ]
