# Generated by Django 2.2.3 on 2020-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/image/default.png', upload_to='media/image/%Y/%m'),
        ),
    ]
