# Generated by Django 2.2.3 on 2020-06-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200602_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='邮箱'),
        ),
    ]
